// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mwdev22/matchmaking"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMatchMaker creates a new instance of MockMatchMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchMaker {
	mock := &MockMatchMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMatchMaker is an autogenerated mock type for the MatchMaker type
type MockMatchMaker struct {
	mock.Mock
}

type MockMatchMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchMaker) EXPECT() *MockMatchMaker_Expecter {
	return &MockMatchMaker_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMatchMaker
func (_mock *MockMatchMaker) Create(players []*matchmaking.Player, mode matchmaking.GameMode, region matchmaking.Region) (*matchmaking.Match, error) {
	ret := _mock.Called(players, mode, region)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *matchmaking.Match
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]*matchmaking.Player, matchmaking.GameMode, matchmaking.Region) (*matchmaking.Match, error)); ok {
		return returnFunc(players, mode, region)
	}
	if returnFunc, ok := ret.Get(0).(func([]*matchmaking.Player, matchmaking.GameMode, matchmaking.Region) *matchmaking.Match); ok {
		r0 = returnFunc(players, mode, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*matchmaking.Match)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*matchmaking.Player, matchmaking.GameMode, matchmaking.Region) error); ok {
		r1 = returnFunc(players, mode, region)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMatchMaker_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMatchMaker_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - players []*matchmaking.Player
//   - mode matchmaking.GameMode
//   - region matchmaking.Region
func (_e *MockMatchMaker_Expecter) Create(players interface{}, mode interface{}, region interface{}) *MockMatchMaker_Create_Call {
	return &MockMatchMaker_Create_Call{Call: _e.mock.On("Create", players, mode, region)}
}

func (_c *MockMatchMaker_Create_Call) Run(run func(players []*matchmaking.Player, mode matchmaking.GameMode, region matchmaking.Region)) *MockMatchMaker_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*matchmaking.Player
		if args[0] != nil {
			arg0 = args[0].([]*matchmaking.Player)
		}
		var arg1 matchmaking.GameMode
		if args[1] != nil {
			arg1 = args[1].(matchmaking.GameMode)
		}
		var arg2 matchmaking.Region
		if args[2] != nil {
			arg2 = args[2].(matchmaking.Region)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMatchMaker_Create_Call) Return(match *matchmaking.Match, err error) *MockMatchMaker_Create_Call {
	_c.Call.Return(match, err)
	return _c
}

func (_c *MockMatchMaker_Create_Call) RunAndReturn(run func(players []*matchmaking.Player, mode matchmaking.GameMode, region matchmaking.Region) (*matchmaking.Match, error)) *MockMatchMaker_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindForPlayer provides a mock function for the type MockMatchMaker
func (_mock *MockMatchMaker) FindForPlayer(player *matchmaking.Player, mode matchmaking.GameMode, region matchmaking.Region) (*matchmaking.Match, error) {
	ret := _mock.Called(player, mode, region)

	if len(ret) == 0 {
		panic("no return value specified for FindForPlayer")
	}

	var r0 *matchmaking.Match
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*matchmaking.Player, matchmaking.GameMode, matchmaking.Region) (*matchmaking.Match, error)); ok {
		return returnFunc(player, mode, region)
	}
	if returnFunc, ok := ret.Get(0).(func(*matchmaking.Player, matchmaking.GameMode, matchmaking.Region) *matchmaking.Match); ok {
		r0 = returnFunc(player, mode, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*matchmaking.Match)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*matchmaking.Player, matchmaking.GameMode, matchmaking.Region) error); ok {
		r1 = returnFunc(player, mode, region)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMatchMaker_FindForPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindForPlayer'
type MockMatchMaker_FindForPlayer_Call struct {
	*mock.Call
}

// FindForPlayer is a helper method to define mock.On call
//   - player *matchmaking.Player
//   - mode matchmaking.GameMode
//   - region matchmaking.Region
func (_e *MockMatchMaker_Expecter) FindForPlayer(player interface{}, mode interface{}, region interface{}) *MockMatchMaker_FindForPlayer_Call {
	return &MockMatchMaker_FindForPlayer_Call{Call: _e.mock.On("FindForPlayer", player, mode, region)}
}

func (_c *MockMatchMaker_FindForPlayer_Call) Run(run func(player *matchmaking.Player, mode matchmaking.GameMode, region matchmaking.Region)) *MockMatchMaker_FindForPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *matchmaking.Player
		if args[0] != nil {
			arg0 = args[0].(*matchmaking.Player)
		}
		var arg1 matchmaking.GameMode
		if args[1] != nil {
			arg1 = args[1].(matchmaking.GameMode)
		}
		var arg2 matchmaking.Region
		if args[2] != nil {
			arg2 = args[2].(matchmaking.Region)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMatchMaker_FindForPlayer_Call) Return(match *matchmaking.Match, err error) *MockMatchMaker_FindForPlayer_Call {
	_c.Call.Return(match, err)
	return _c
}

func (_c *MockMatchMaker_FindForPlayer_Call) RunAndReturn(run func(player *matchmaking.Player, mode matchmaking.GameMode, region matchmaking.Region) (*matchmaking.Match, error)) *MockMatchMaker_FindForPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMatchNotification provides a mock function for the type MockMatchMaker
func (_mock *MockMatchMaker) NewMatchNotification(match *matchmaking.Match) error {
	ret := _mock.Called(match)

	if len(ret) == 0 {
		panic("no return value specified for NewMatchNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*matchmaking.Match) error); ok {
		r0 = returnFunc(match)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMatchMaker_NewMatchNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewMatchNotification'
type MockMatchMaker_NewMatchNotification_Call struct {
	*mock.Call
}

// NewMatchNotification is a helper method to define mock.On call
//   - match *matchmaking.Match
func (_e *MockMatchMaker_Expecter) NewMatchNotification(match interface{}) *MockMatchMaker_NewMatchNotification_Call {
	return &MockMatchMaker_NewMatchNotification_Call{Call: _e.mock.On("NewMatchNotification", match)}
}

func (_c *MockMatchMaker_NewMatchNotification_Call) Run(run func(match *matchmaking.Match)) *MockMatchMaker_NewMatchNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *matchmaking.Match
		if args[0] != nil {
			arg0 = args[0].(*matchmaking.Match)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMatchMaker_NewMatchNotification_Call) Return(err error) *MockMatchMaker_NewMatchNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMatchMaker_NewMatchNotification_Call) RunAndReturn(run func(match *matchmaking.Match) error) *MockMatchMaker_NewMatchNotification_Call {
	_c.Call.Return(run)
	return _c
}
