// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mwdev22/matchmaking"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// MatchCreated provides a mock function for the type MockNotifier
func (_mock *MockNotifier) MatchCreated(match *matchmaking.Match) error {
	ret := _mock.Called(match)

	if len(ret) == 0 {
		panic("no return value specified for MatchCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*matchmaking.Match) error); ok {
		r0 = returnFunc(match)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifier_MatchCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchCreated'
type MockNotifier_MatchCreated_Call struct {
	*mock.Call
}

// MatchCreated is a helper method to define mock.On call
//   - match *matchmaking.Match
func (_e *MockNotifier_Expecter) MatchCreated(match interface{}) *MockNotifier_MatchCreated_Call {
	return &MockNotifier_MatchCreated_Call{Call: _e.mock.On("MatchCreated", match)}
}

func (_c *MockNotifier_MatchCreated_Call) Run(run func(match *matchmaking.Match)) *MockNotifier_MatchCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *matchmaking.Match
		if args[0] != nil {
			arg0 = args[0].(*matchmaking.Match)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_MatchCreated_Call) Return(err error) *MockNotifier_MatchCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifier_MatchCreated_Call) RunAndReturn(run func(match *matchmaking.Match) error) *MockNotifier_MatchCreated_Call {
	_c.Call.Return(run)
	return _c
}
