// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mwdev22/matchmaking"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// AddPlayer provides a mock function for the type MockQueue
func (_mock *MockQueue) AddPlayer(player *matchmaking.Player) error {
	ret := _mock.Called(player)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*matchmaking.Player) error); ok {
		r0 = returnFunc(player)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_AddPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlayer'
type MockQueue_AddPlayer_Call struct {
	*mock.Call
}

// AddPlayer is a helper method to define mock.On call
//   - player *matchmaking.Player
func (_e *MockQueue_Expecter) AddPlayer(player interface{}) *MockQueue_AddPlayer_Call {
	return &MockQueue_AddPlayer_Call{Call: _e.mock.On("AddPlayer", player)}
}

func (_c *MockQueue_AddPlayer_Call) Run(run func(player *matchmaking.Player)) *MockQueue_AddPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *matchmaking.Player
		if args[0] != nil {
			arg0 = args[0].(*matchmaking.Player)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueue_AddPlayer_Call) Return(err error) *MockQueue_AddPlayer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_AddPlayer_Call) RunAndReturn(run func(player *matchmaking.Player) error) *MockQueue_AddPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// Capacity provides a mock function for the type MockQueue
func (_mock *MockQueue) Capacity() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capacity")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockQueue_Capacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capacity'
type MockQueue_Capacity_Call struct {
	*mock.Call
}

// Capacity is a helper method to define mock.On call
func (_e *MockQueue_Expecter) Capacity() *MockQueue_Capacity_Call {
	return &MockQueue_Capacity_Call{Call: _e.mock.On("Capacity")}
}

func (_c *MockQueue_Capacity_Call) Run(run func()) *MockQueue_Capacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_Capacity_Call) Return(n int) *MockQueue_Capacity_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockQueue_Capacity_Call) RunAndReturn(run func() int) *MockQueue_Capacity_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayers provides a mock function for the type MockQueue
func (_mock *MockQueue) GetPlayers() []*matchmaking.Player {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPlayers")
	}

	var r0 []*matchmaking.Player
	if returnFunc, ok := ret.Get(0).(func() []*matchmaking.Player); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*matchmaking.Player)
		}
	}
	return r0
}

// MockQueue_GetPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayers'
type MockQueue_GetPlayers_Call struct {
	*mock.Call
}

// GetPlayers is a helper method to define mock.On call
func (_e *MockQueue_Expecter) GetPlayers() *MockQueue_GetPlayers_Call {
	return &MockQueue_GetPlayers_Call{Call: _e.mock.On("GetPlayers")}
}

func (_c *MockQueue_GetPlayers_Call) Run(run func()) *MockQueue_GetPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_GetPlayers_Call) Return(players []*matchmaking.Player) *MockQueue_GetPlayers_Call {
	_c.Call.Return(players)
	return _c
}

func (_c *MockQueue_GetPlayers_Call) RunAndReturn(run func() []*matchmaking.Player) *MockQueue_GetPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// OpenSlots provides a mock function for the type MockQueue
func (_mock *MockQueue) OpenSlots() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenSlots")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockQueue_OpenSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenSlots'
type MockQueue_OpenSlots_Call struct {
	*mock.Call
}

// OpenSlots is a helper method to define mock.On call
func (_e *MockQueue_Expecter) OpenSlots() *MockQueue_OpenSlots_Call {
	return &MockQueue_OpenSlots_Call{Call: _e.mock.On("OpenSlots")}
}

func (_c *MockQueue_OpenSlots_Call) Run(run func()) *MockQueue_OpenSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_OpenSlots_Call) Return(n int) *MockQueue_OpenSlots_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockQueue_OpenSlots_Call) RunAndReturn(run func() int) *MockQueue_OpenSlots_Call {
	_c.Call.Return(run)
	return _c
}

// PlayerCount provides a mock function for the type MockQueue
func (_mock *MockQueue) PlayerCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PlayerCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockQueue_PlayerCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlayerCount'
type MockQueue_PlayerCount_Call struct {
	*mock.Call
}

// PlayerCount is a helper method to define mock.On call
func (_e *MockQueue_Expecter) PlayerCount() *MockQueue_PlayerCount_Call {
	return &MockQueue_PlayerCount_Call{Call: _e.mock.On("PlayerCount")}
}

func (_c *MockQueue_PlayerCount_Call) Run(run func()) *MockQueue_PlayerCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_PlayerCount_Call) Return(n int) *MockQueue_PlayerCount_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockQueue_PlayerCount_Call) RunAndReturn(run func() int) *MockQueue_PlayerCount_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePlayer provides a mock function for the type MockQueue
func (_mock *MockQueue) RemovePlayer(playerID string) error {
	ret := _mock.Called(playerID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePlayer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(playerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_RemovePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePlayer'
type MockQueue_RemovePlayer_Call struct {
	*mock.Call
}

// RemovePlayer is a helper method to define mock.On call
//   - playerID string
func (_e *MockQueue_Expecter) RemovePlayer(playerID interface{}) *MockQueue_RemovePlayer_Call {
	return &MockQueue_RemovePlayer_Call{Call: _e.mock.On("RemovePlayer", playerID)}
}

func (_c *MockQueue_RemovePlayer_Call) Run(run func(playerID string)) *MockQueue_RemovePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueue_RemovePlayer_Call) Return(err error) *MockQueue_RemovePlayer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_RemovePlayer_Call) RunAndReturn(run func(playerID string) error) *MockQueue_RemovePlayer_Call {
	_c.Call.Return(run)
	return _c
}
